name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install elan
      run: |
        curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
        echo "$HOME/.elan/bin" >> $GITHUB_PATH
    
    - name: Install Lean toolchain
      run: |
        elan toolchain install $(cat lean-toolchain)
        elan default $(cat lean-toolchain)
    
    - name: Cache Lake dependencies
      uses: actions/cache@v3
      with:
        path: .lake
        key: ${{ runner.os }}-lake-${{ hashFiles('lake-manifest.json') }}
        restore-keys: |
          ${{ runner.os }}-lake-
    
    - name: Build project
      run: lake build
    
    - name: Run tests (if any)
      run: |
        if [ -f "test_integration.lean" ]; then
          lake build test_integration.lean:olean || echo "Test file not configured as target"
        fi 